namespace BGME.Framework.P3R.SMT5V.Types;

public enum E_BTL_SYMBOL_ENCOUNT : byte
{
    E_BTL_SYMBOL_ENCOUNT_NORMAL = 0,
    E_BTL_SYMBOL_ENCOUNT_PLAYER_ATTACK = 1,
    E_BTL_SYMBOL_ENCOUNT_ENEMY_BACK = 2,
    E_BTL_SYMBOL_ENCOUNT_MAX = 3,
};
